// <auto-generated />
namespace MoneyManager.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddRepeatTransaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRepeatTransaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201703301940384_AddRepeatTransaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
